services:
  search:
    build:
      context: ./search
      dockerfile: Dockerfile

    environment:
      MONGO_URL: mongodb://mongo:27017/hotel-app
      REDIS_URL: redis://redis:6379

    depends_on:
      - mongo
      - redis

    expose:
      - "3001"

  bookings:
    build:
      context: ./booking
      dockerfile: Dockerfile

    environment:
      MONGO_URL: mongodb://mongo:27017/hotel-app
      REDIS_URL: redis://redis:6379

    depends_on:
      - mongo
      - redis

    expose:
      - "3002"

  users:
    build:
      context: ./users
      dockerfile: Dockerfile

    environment:
      MONGO_URL: mongodb://mongo:27017/hotel-app

    depends_on:
      - mongo

    expose:
      - "3000"

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile

    environment:
      MONGO_URL: mongodb://mongo:27017/hotel-app
      REDIS_URL: redis://redis:6379

    depends_on:
      - mongo
      - redis
      - bookings

  nginx:
    image: nginx:latest

    ports:
      - "3000:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - search
      - users
      - bookings

  mongo:
    image: mongo:latest
    container_name: hotel-app-mongodb


    volumes:
      - mongo_data:/data/db
      - ./init_hotels.sh:/docker-entrypoint-initdb.d/init_hotels.sh:ro

  redis:
    image: redis:latest
    container_name: hotel-app-redis



volumes:
  mongo_data: